import type { McpServer } from '@modelcontextprotocol/server';
import {
  setResourceKey,
  type Approver,
  type ConfirmationStore,
} from 'mcp-approval';
import { z } from 'zod';
import { redactSecrets } from '../redact.js';
import {
  errorResult,
  run,
  textResult,
  upstreamJsonResult,
  upstreamTextResult,
} from '../result.js';

import type { WgEasyApi } from '../api.js';
import { READ_ONLY } from './annotations.js';

/**
 * A client id, as a number or as the decimal string a client may send instead.
 *
 * Spelled out rather than left to `z.coerce.number()`, which is `Number()` and
 * therefore accepts far more than a number: `Number(true)` is `1` and
 * `Number(['3'])` is `3`, so `{clientId: true}` used to address the first
 * client on the instance. Nothing legitimate sends those, and on a VPN a
 * silently reinterpreted target is the wrong kind of forgiving.
 */
const clientId = z
  .union([
    z.number().int().positive(),
    z
      .string()
      .regex(/^\d+$/)
      .transform(Number)
      .refine((value) => value > 0),
  ])
  .describe('Numeric ID of the client (see list_clients)');

const confirmToken = z
  .string()
  .trim()
  .regex(/^[a-f0-9]{32}$/)
  .optional()
  .describe('The token from this tool’s previous, unconfirmed response.');

/**
 * Fields of the wg-easy `ClientUpdateSchema`. The update endpoint expects the
 * complete object, so `update_client` merges partial input into the current
 * client state before posting.
 */
const UPDATABLE_FIELDS = [
  'name',
  'enabled',
  'expiresAt',
  'ipv4Address',
  'ipv6Address',
  'preUp',
  'postUp',
  'preDown',
  'postDown',
  'allowedIps',
  'serverAllowedIps',
  'firewallIps',
  'mtu',
  'jC',
  'jMin',
  'jMax',
  'i1',
  'i2',
  'i3',
  'i4',
  'i5',
  'persistentKeepalive',
  'serverEndpoint',
  'dns',
] as const;

/**
 * A client row as far as `generate_one_time_link` cares about it.
 *
 * `oneTimeLink` is a joined row on wg-easy 15 and a bare string on older
 * builds, so both shapes are accepted.
 */
interface OneTimeLinkClient {
  id?: number;
  oneTimeLink?: { oneTimeLink?: string; expiresAt?: string } | string | null;
}

/** The display name of a client, for the caller-supplied lines of a prompt. */
async function clientName(api: WgEasyApi, id: number): Promise<string> {
  // Also the existence check: a missing client fails here with the API's own
  // error, before anybody is asked to approve something that cannot happen.
  const client = (await api.get(`/api/client/${id}`)) as { name?: unknown };
  return typeof client.name === 'string' ? client.name : `#${id}`;
}

export function registerClientTools(
  server: McpServer,
  api: WgEasyApi,
  confirmations: ConfirmationStore,
  approval: Approver
): void {
  server.registerTool(
    'list_clients',
    {
      title: 'List WireGuard clients',
      description:
        'List all WireGuard clients of the wg-easy instance, including their status (enabled/expired), addresses and traffic statistics.',
      inputSchema: z.object({
        filter: z
          .string()
          .optional()
          .describe('Optional name filter (substring match)'),
        sort: z
          .enum(['asc', 'desc'])
          .optional()
          .describe('Sort by name, ascending or descending'),
      }),
      annotations: READ_ONLY,
    },
    ({ filter, sort }) =>
      run(async () => {
        const query = new URLSearchParams();
        if (filter) query.set('filter', filter);
        if (sort) query.set('sort', sort);
        const suffix = query.size > 0 ? `?${query.toString()}` : '';
        return upstreamJsonResult(
          redactSecrets(await api.get(`/api/client${suffix}`)),
          'Narrow the result with the filter argument, or fetch a single client with get_client.'
        );
      })
  );

  server.registerTool(
    'get_client',
    {
      title: 'Get WireGuard client',
      description:
        'Get the full details of a single WireGuard client.\n\n' +
        'The private key and pre-shared key are redacted. They are not missing ' +
        'from the instance — wg-easy returns them here in full, and this ' +
        'server removes them, because a key in the conversation is a key in ' +
        'the transcript. Use get_client_config or get_client_qrcode when the ' +
        'key is genuinely wanted: handing a peer its configuration is what ' +
        'those two are for.',
      inputSchema: z.object({ clientId }),
      annotations: READ_ONLY,
    },
    ({ clientId }) =>
      run(async () =>
        upstreamJsonResult(
          redactSecrets(await api.get(`/api/client/${clientId}`)),
          'Fetch the configuration file separately with get_client_config.'
        )
      )
  );

  server.registerTool(
    'create_client',
    {
      title: 'Create WireGuard client',
      description:
        'Create a new WireGuard client. Keys and IP addresses are generated by wg-easy. Returns the new client ID. Asks a person first; where the client cannot show a dialog, call once to receive a token and again with it.',
      inputSchema: z.object({
        name: z.string().min(1).describe('Display name of the new client'),
        expiresAt: z
          .string()
          .optional()
          .describe(
            'Optional expiry date as ISO string (e.g. 2026-12-31). Omit for no expiry.'
          ),
        confirm_token: confirmToken,
      }),
      annotations: {
        // Additive: it grants a new VPN identity and takes nothing away. Not
        // idempotent — wg-easy keys clients by an id it generates, so calling
        // twice leaves two clients with two key pairs.
        //
        // Guarded all the same, and not for the reason destructiveHint carries:
        // this issues a credential that reaches the network behind the VPN. The
        // annotation says what a call destroys; the dialog decides what a call
        // is allowed to grant.
        readOnlyHint: false,
        destructiveHint: false,
        idempotentHint: false,
        openWorldHint: false,
      },
    },
    async ({ name, expiresAt, confirm_token }, mcp) =>
      run(async () => {
        const outcome = await approval.requestApproval(
          server,
          mcp,
          confirmations,
          {
            what: 'create a new WireGuard client',
            consequence:
              'It receives its own key pair and can connect to every ' +
              'network this VPN reaches. Deleting it later does not undo a ' +
              'connection it made in the meantime.',
            resourceKey: setResourceKey('create_client', [
              name,
              expiresAt ?? '',
            ]),
            token: confirm_token,
            details: [
              { label: 'Name', value: name },
              { label: 'Expires', value: expiresAt ?? 'never' },
            ],
            toolName: 'create_client',
            title: 'Create this VPN client?',
            hint: 'Tick to create it, leave it to cancel.',
          }
        );
        if (outcome.decision === 'rejected') return errorResult(outcome.reason);
        if (outcome.decision === 'declined') {
          return errorResult('The user declined. create_client did nothing.');
        }
        if (outcome.decision === 'pending') return outcome.result;

        return upstreamJsonResult(
          redactSecrets(
            await api.post('/api/client', {
              name,
              expiresAt: expiresAt ?? null,
            })
          ),
          'Re-read the new client with get_client.'
        );
      })
  );

  server.registerTool(
    'update_client',
    {
      title: 'Update WireGuard client',
      description:
        'Update a WireGuard client. Only the provided fields are changed; all other settings are preserved. Asks a person first; where the client cannot show a dialog, call once to receive a token and again with it.',
      inputSchema: z.object({
        clientId,
        confirm_token: confirmToken,
        name: z.string().min(1).optional().describe('New display name'),
        enabled: z
          .boolean()
          .optional()
          .describe('Enable or disable the client'),
        expiresAt: z
          .string()
          .nullable()
          .optional()
          .describe('Expiry date as ISO string, or null to remove the expiry'),
        ipv4Address: z
          .string()
          .optional()
          .describe('IPv4 address of the client'),
        ipv6Address: z
          .string()
          .optional()
          .describe('IPv6 address of the client'),
        allowedIps: z
          .array(z.string())
          .nullable()
          .optional()
          .describe(
            'CIDRs routed through the tunnel on the client side, or null to use the server default'
          ),
        serverAllowedIps: z
          .array(z.string())
          .optional()
          .describe('Additional CIDRs the server routes to this client'),
        dns: z
          .array(z.string())
          .nullable()
          .optional()
          .describe(
            'DNS servers for the client, or null to use the server default'
          ),
        mtu: z.number().int().optional().describe('MTU for the client'),
        persistentKeepalive: z
          .number()
          .int()
          .optional()
          .describe('Persistent keepalive interval in seconds (0 = off)'),
      }),
      annotations: {
        // Destructive: the fields it is given replace what was there, and an
        // address or allowed-IP range that is overwritten is not recoverable
        // from here. Only the provided fields change, so sending the same call
        // twice lands on the same client.
        readOnlyHint: false,
        destructiveHint: true,
        idempotentHint: true,
        openWorldHint: false,
      },
    },
    async ({ clientId, confirm_token, ...changes }, mcp) =>
      run(async () => {
        // Bound to the exact edit, not merely to the client: approving a name
        // change must not license a later call that moves the address or
        // widens serverAllowedIps. `setResourceKey` sorts and fingerprints,
        // so the key does not depend on the order the fields arrived in.
        const edit = Object.entries(changes)
          .filter(([, value]) => value !== undefined)
          .map(([key, value]) => `${key}=${JSON.stringify(value)}`);
        const outcome = await approval.requestApproval(
          server,
          mcp,
          confirmations,
          {
            what: `change WireGuard client ${clientId}`,
            consequence:
              'The fields listed below replace what is there now. An address ' +
              'or an allowed-IP range that is overwritten cannot be read back ' +
              'from here.',
            resourceKey: setResourceKey('update_client', [
              String(clientId),
              ...edit,
            ]),
            token: confirm_token,
            details: [
              { label: 'Client', value: await clientName(api, clientId) },
              { label: 'Changes', value: edit.join(', ') || '(none)' },
            ],
            toolName: 'update_client',
            title: `Change client ${clientId}?`,
            hint: 'Tick to apply the change, leave it to cancel.',
          }
        );
        if (outcome.decision === 'rejected') return errorResult(outcome.reason);
        if (outcome.decision === 'declined') {
          return errorResult('The user declined. update_client did nothing.');
        }
        if (outcome.decision === 'pending') return outcome.result;

        // The API expects the complete update object, so merge the partial
        // input into the current client state.
        const current = (await api.get(`/api/client/${clientId}`)) as Record<
          string,
          unknown
        >;
        const body: Record<string, unknown> = {};
        for (const field of UPDATABLE_FIELDS) {
          body[field] = current[field] ?? null;
        }
        for (const [key, value] of Object.entries(changes)) {
          if (value !== undefined) body[key] = value;
        }
        return upstreamJsonResult(
          redactSecrets(await api.post(`/api/client/${clientId}`, body)),
          'Re-read the client with get_client.'
        );
      })
  );

  server.registerTool(
    'enable_client',
    {
      title: 'Enable WireGuard client',
      description:
        'Enable a WireGuard client so it can connect again. Asks a person first; where the client cannot show a dialog, call once to receive a token and again with it.',
      inputSchema: z.object({ clientId, confirm_token: confirmToken }),
      annotations: {
        // Restores access rather than removing it, so nothing here is
        // destructive.
        //
        // Guarded all the same, for `create_client`'s reason rather than
        // `delete_client`'s: this re-arms a credential that is already
        // installed on a peer and reaches every network behind the VPN. If
        // `disable_client` is the reversible revocation this server recommends
        // — and its own catalogue says it is — then enabling is the undo of a
        // revocation, and the undo cannot be the cheaper call. Leaving it
        // ungated also made the guard on `update_client({enabled: true})`
        // avoidable by picking the other tool for the same state change.
        readOnlyHint: false,
        destructiveHint: false,
        idempotentHint: true,
        openWorldHint: false,
      },
    },
    async ({ clientId, confirm_token }, mcp) =>
      run(async () => {
        const outcome = await approval.requestApproval(
          server,
          mcp,
          confirmations,
          {
            what: `enable WireGuard client ${clientId}`,
            consequence:
              'This client’s existing key pair can reach every network this ' +
              'VPN reaches again. The configuration is already installed on ' +
              'the peer, so nothing further has to be handed over for it to ' +
              'connect.',
            resourceKey: setResourceKey('enable_client', [String(clientId)]),
            token: confirm_token,
            details: [
              { label: 'Client', value: await clientName(api, clientId) },
            ],
            toolName: 'enable_client',
            title: `Enable client ${clientId}?`,
            hint: 'Tick to enable it, leave it to cancel.',
          }
        );
        if (outcome.decision === 'rejected') return errorResult(outcome.reason);
        if (outcome.decision === 'declined') {
          return errorResult('The user declined. enable_client did nothing.');
        }
        if (outcome.decision === 'pending') return outcome.result;

        return upstreamJsonResult(
          redactSecrets(await api.post(`/api/client/${clientId}/enable`)),
          'Re-read the client with get_client.'
        );
      })
  );

  server.registerTool(
    'disable_client',
    {
      title: 'Disable WireGuard client',
      description:
        'Disable a WireGuard client. The client keeps its configuration but can no longer connect.',
      inputSchema: z.object({ clientId }),
      annotations: {
        // Not destructive: the client and its keys stay, only the tunnel stops.
        // enable_client puts it back.
        //
        // Ungated on purpose, and the asymmetry with enable_client is the
        // point: this one only ever withdraws access. Making the safe half of
        // a revoke/restore pair ask a person would put a dialog between an
        // operator and cutting off a peer they have just decided to cut off.
        readOnlyHint: false,
        destructiveHint: false,
        idempotentHint: true,
        openWorldHint: false,
      },
    },
    ({ clientId }) =>
      run(async () =>
        upstreamJsonResult(
          redactSecrets(await api.post(`/api/client/${clientId}/disable`)),
          'Re-read the client with get_client.'
        )
      )
  );

  server.registerTool(
    'delete_client',
    {
      title: 'Delete WireGuard client',
      description:
        'Permanently delete a WireGuard client. This is irreversible: the client loses VPN access and its keys cannot be restored. Asks a person first; where the client cannot show a dialog, call once to receive a token and again with it.',
      inputSchema: z.object({
        clientId,
        confirm_token: confirmToken,
      }),
      annotations: {
        // Idempotent by the specification's wording — "no additional effect on
        // its environment". The second call fails, but the world is the same
        // either way, which is what lets a client retry after a timeout.
        readOnlyHint: false,
        destructiveHint: true,
        idempotentHint: true,
        openWorldHint: false,
      },
    },
    async ({ clientId, confirm_token }, mcp) =>
      run(async () => {
        const outcome = await approval.requestApproval(
          server,
          mcp,
          confirmations,
          {
            what: `delete WireGuard client ${clientId}`,
            consequence:
              'Its key pair is destroyed and cannot be restored. Anyone using ' +
              'that configuration loses VPN access, and re-creating the client ' +
              'gives them a different key they have to install.',
            resourceKey: setResourceKey('delete_client', [String(clientId)]),
            token: confirm_token,
            details: [
              { label: 'Client', value: await clientName(api, clientId) },
            ],
            toolName: 'delete_client',
            title: `Delete client ${clientId}?`,
            hint: 'Tick to delete it, leave it to cancel.',
          }
        );
        if (outcome.decision === 'rejected') return errorResult(outcome.reason);
        if (outcome.decision === 'declined') {
          return errorResult('The user declined. delete_client did nothing.');
        }
        if (outcome.decision === 'pending') return outcome.result;

        await api.delete(`/api/client/${clientId}`);
        return textResult(`Client ${clientId} deleted.`);
      })
  );

  server.registerTool(
    'get_client_config',
    {
      title: 'Get WireGuard client configuration',
      description:
        'Get the WireGuard configuration file (wg .conf format) for a client. SENSITIVE: the output contains the client private key — treat it as a secret and do not repeat it unnecessarily.',
      inputSchema: z.object({ clientId }),
      annotations: READ_ONLY,
    },
    ({ clientId }) =>
      run(async () =>
        upstreamTextResult(
          String(await api.get(`/api/client/${clientId}/configuration`)),
          'Download the configuration from the wg-easy UI if it was cut off.'
        )
      )
  );

  server.registerTool(
    'get_client_qrcode',
    {
      title: 'Get WireGuard client QR code',
      description:
        'Get the client configuration as a QR code (SVG markup) for scanning with the WireGuard mobile app. SENSITIVE: the QR code encodes the client private key — treat it as a secret.',
      inputSchema: z.object({ clientId }),
      annotations: READ_ONLY,
    },
    ({ clientId }) =>
      run(async () =>
        upstreamTextResult(
          String(await api.get(`/api/client/${clientId}/qrcode.svg`)),
          'Use get_client_config instead if the QR code markup was cut off.'
        )
      )
  );

  server.registerTool(
    'generate_one_time_link',
    {
      title: 'Generate one-time config link',
      description:
        'Generate a one-time download link for a client configuration that can ' +
        'be shared with the end user. SENSITIVE: anyone with the link can ' +
        'download the full client configuration without authentication — share ' +
        'it only with the intended user. The link expires after five minutes. ' +
        'Asks a person first; where the client cannot show a dialog, call once ' +
        'to receive a token and again with it.\n\n' +
        'If the answer says the link value could not be read back, the link ' +
        'still exists on the instance and is downloadable by anyone who has ' +
        'the URL. Say so rather than reporting that nothing happened, and ' +
        'point at the wg-easy UI, where it can be revoked.',
      inputSchema: z.object({ clientId, confirm_token: confirmToken }),
      annotations: {
        // Destroys nothing, and that is the whole difficulty with this one: it
        // mints a URL that hands the full client configuration — private key
        // included — to anyone who has it, without authentication.
        // destructiveHint is the wrong axis for that risk, which is why the
        // tool is guarded instead. Not idempotent: each call issues a fresh
        // link, and the previous one stops working.
        readOnlyHint: false,
        destructiveHint: false,
        idempotentHint: false,
        openWorldHint: false,
      },
    },
    async ({ clientId, confirm_token }, mcp) =>
      run(async () => {
        const outcome = await approval.requestApproval(
          server,
          mcp,
          confirmations,
          {
            what: `issue a one-time download link for client ${clientId}`,
            consequence:
              'Anyone who has the URL can download that client’s full ' +
              'configuration, private key included, without logging in. The ' +
              'link cannot be withdrawn once it has been passed on.',
            resourceKey: setResourceKey('generate_one_time_link', [
              String(clientId),
            ]),
            token: confirm_token,
            details: [
              { label: 'Client', value: await clientName(api, clientId) },
            ],
            toolName: 'generate_one_time_link',
            title: `Issue a download link for client ${clientId}?`,
            hint: 'Tick to issue the link, leave it to cancel.',
          }
        );
        if (outcome.decision === 'rejected') return errorResult(outcome.reason);
        if (outcome.decision === 'declined') {
          return errorResult(
            'The user declined. generate_one_time_link did nothing.'
          );
        }
        if (outcome.decision === 'pending') return outcome.result;

        await api.post(`/api/client/${clientId}/generateOneTimeLink`);

        // Past this point the link exists on the instance, whatever happens
        // below. The read-back is a second request and can fail on its own —
        // and if that failure were allowed to reach `run()`, the answer would
        // be a bare transport error saying only that a GET failed. A model
        // reads that as "no link was made" while an unauthenticated URL
        // serving the full configuration, private key included, is live for
        // the next five minutes. Report the mint first, then the failure.
        let clients: OneTimeLinkClient[];
        try {
          // The **list**, not `/api/client/{id}`. wg-easy joins the one-time
          // link onto the client row in `findMany` and not in `findById`, so
          // the single-client read answers `oneTimeLink: null` for a client
          // that has a live link — verified against 15.4.0. Reading the single
          // client here is what made this tool report "the link value was not
          // returned by the API" on every successful call, and what the tool's
          // own description used to explain as wg-easy answering HTTP 500. It
          // does not: the POST answers 200 and the link works.
          clients = (await api.get('/api/client')) as OneTimeLinkClient[];
        } catch (error) {
          const message =
            error instanceof Error ? error.message : String(error);
          return textResult(
            `The one-time link for client ${clientId} was created, but reading ` +
              `it back failed: ${message}. The link exists on the instance ` +
              'even though its value is not available here. Check the wg-easy ' +
              'UI and revoke the link if it was not intended.'
          );
        }
        const found = Array.isArray(clients)
          ? clients.find((entry) => entry?.id === clientId)
          : undefined;
        // Accepts both shapes: 15.4.0 nests the value in a joined row, older
        // builds put the string on the client directly.
        const record = found?.oneTimeLink;
        const link = typeof record === 'string' ? record : record?.oneTimeLink;
        const expiresAt =
          typeof record === 'string' ? null : (record?.expiresAt ?? null);
        if (!link) {
          return textResult(
            `The one-time link for client ${clientId} was created, but its ` +
              'value was not in the client list. The link exists on the ' +
              'instance and can be downloaded by anyone who has the URL. ' +
              'Check the wg-easy UI and revoke it if it was not intended.'
          );
        }
        return upstreamJsonResult(
          {
            success: true,
            oneTimeLink: link,
            path: `/cnf/${link}`,
            expiresAt,
          },
          'Re-read the client with get_client.'
        );
      })
  );
}
